version: '3.5'
services:

  debito:
    container_name: app-debito
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    networks:
      - net-driver
      - eureka_net-driver
      #- prometheus_net-driver
    external_links:
      - eureka:eureka
      #- prometheus:prometheus
    depends_on:
      - db
    links:
      - db
    restart: on-failure

  db:
    image: mysql
    container_name: dbdebito
    hostname: dbdebito
    restart: always
    networks:
      - net-driver
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: debitodb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  net-driver:
    driver: bridge
  eureka_net-driver:
    external: true
  #prometheus_net-driver:
    #external: true
