version: '3.4'
services:

  debito:
    container_name: app-debito
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    networks:
      - net-exemplo
    depends_on:
      - db
    links:
      - db
    restart: on-failure

  db:
    image: mysql
    container_name: dbdebito
    hostname: dbdebito
    restart: always
    networks:
      - net-exemplo
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: debitodb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  net-exemplo:
    driver: bridge
